### ISSUE TITLE
Add video streaming functionality from Misty's RGB camera

### ISSUE THREAD

**Issue by kalebishop** [NSF-iSAT/misty_woz_local#3]
Use OpenCV for Python to stream from Misty's camera (by treating Misty as a media server) to a window, either separate from the GUI or (preferably) embedded within.
You should be able to do something very similar to [this (somewhat simpler) controller someone else wrote for Misty](https://github.com/CPsridharCP/MistySkills/tree/master/Apps/Teleop/02_pythonTeleop). *Note that the Misty API has changed somewhat since this was created, which is why we had to re-implement stuff like the text-to-speech. However, all the CV video processing he does should hold up.

**Comment by lara264** [comment]
I've started adding cv2 video capture, but I'm running into "connection refused" issues when I run the code. I can open the video stream using VLC, so I know the ip and port are correct.

**Comment by kalebishop** [comment]
@lara264 quick fix (on top of what we talked about earlier): try adding a call like `time.sleep(2)` between your calls to `startAvStream` and `cv2.VideoCapture`, to allow Misty a moment to open up the stream and start accepting connections

**Comment by lara264** [comment]
Adding time.sleep(2) between the two calls worked!

**Comment by kalebishop** [comment]
#8 Closed

**Comment by kalebishop** [comment]
#8 closed
